package com.freedomplay.app.data.api.piped

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test

class PipedDtoTest {

    @Test
    fun `PipedVideoResponse defaults`() {
        val response = PipedVideoResponse()
        assertEquals(null, response.title)
        assertEquals(null, response.uploader)
        assertEquals(null, response.videoStreams)
        assertEquals(null, response.audioStreams)
        assertEquals(null, response.livestream)
    }

    @Test
    fun `PipedVideoResponse with values`() {
        val response = PipedVideoResponse(
            title = "Test Video",
            uploader = "Test Channel",
            duration = 120L,
            views = 1000L,
            videoStreams = listOf(
                PipedStream(url = "https://example.com/video", quality = "720p", mimeType = "video/mp4")
            ),
            audioStreams = listOf(
                PipedStream(url = "https://example.com/audio", quality = "128kbps", mimeType = "audio/mp4")
            ),
            livestream = false
        )
        assertEquals("Test Video", response.title)
        assertEquals("Test Channel", response.uploader)
        assertEquals(120L, response.duration)
        assertEquals(1000L, response.views)
        assertEquals(1, response.videoStreams?.size)
        assertEquals(1, response.audioStreams?.size)
    }

    @Test
    fun `PipedStream defaults`() {
        val stream = PipedStream()
        assertEquals(null, stream.url)
        assertEquals(null, stream.quality)
        assertEquals(null, stream.mimeType)
        assertEquals(null, stream.width)
        assertEquals(null, stream.height)
    }

    @Test
    fun `PipedStream with values`() {
        val stream = PipedStream(
            url = "https://example.com/stream",
            quality = "1080p",
            mimeType = "video/mp4",
            codec = "avc1",
            bitrate = 5000000L,
            width = 1920,
            height = 1080,
            fps = 60
        )
        assertEquals("https://example.com/stream", stream.url)
        assertEquals("1080p", stream.quality)
        assertEquals("video/mp4", stream.mimeType)
        assertEquals("avc1", stream.codec)
        assertEquals(5000000L, stream.bitrate)
        assertEquals(1920, stream.width)
        assertEquals(1080, stream.height)
        assertEquals(60, stream.fps)
    }

    @Test
    fun `PipedSearchResponse defaults`() {
        val response = PipedSearchResponse()
        assertEquals(null, response.items)
        assertEquals(null, response.suggestion)
    }

    @Test
    fun `PipedSearchResponse with items`() {
        val response = PipedSearchResponse(
            items = listOf(
                PipedSearchItem(title = "Result 1", url = "/watch?v=abc12345678"),
                PipedSearchItem(title = "Result 2", url = "/watch?v=def12345678")
            ),
            suggestion = "Did you mean: test"
        )
        assertEquals(2, response.items?.size)
        assertEquals("Result 1", response.items?.get(0)?.title)
        assertEquals("Did you mean: test", response.suggestion)
    }

    @Test
    fun `PipedTrendingResponse defaults`() {
        val response = PipedTrendingResponse()
        assertEquals(null, response.items)
    }

    @Test
    fun `PipedTrendingItem with values`() {
        val item = PipedTrendingItem(
            title = "Trending Video",
            url = "/watch?v=abc12345678",
            thumbnail = "https://img.youtube.com/vi/abc12345678/mqdefault.jpg",
            uploaderName = "Creator",
            views = 50000L,
            duration = 300L
        )
        assertEquals("Trending Video", item.title)
        assertEquals(50000L, item.views)
        assertEquals(300L, item.duration)
    }

    @Test
    fun `PipedSubtitle defaults`() {
        val subtitle = PipedSubtitle()
        assertEquals(null, subtitle.url)
        assertEquals(null, subtitle.code)
        assertEquals(null, subtitle.autoGenerated)
    }

    @Test
    fun `PipedSubtitle with values`() {
        val subtitle = PipedSubtitle(
            url = "https://example.com/subs",
            mimeType = "text/vtt",
            name = "English",
            code = "en",
            autoGenerated = true
        )
        assertEquals("https://example.com/subs", subtitle.url)
        assertEquals("en", subtitle.code)
        assertEquals(true, subtitle.autoGenerated)
    }

    @Test
    fun `PipedChannelResponse defaults`() {
        val response = PipedChannelResponse()
        assertEquals(null, response.name)
        assertEquals(null, response.subscriberCount)
    }

    @Test
    fun `PipedPlaylistResponse defaults`() {
        val response = PipedPlaylistResponse()
        assertEquals(null, response.name)
        assertEquals(null, response.relatedStreams)
    }
}
