package com.freedomplay.app.data.api.piped

import retrofit2.http.GET
import retrofit2.http.Path
import retrofit2.http.Query

data class PipedVideoResponse(
    val title: String? = null,
    val uploader: String? = null,
    val uploaderUrl: String? = null,
    val thumbnailUrl: String? = null,
    val duration: Long? = null,
    val views: Long? = null,
    val uploaded: Long? = null,
    val uploadDate: String? = null,
    val description: String? = null,
    val videoStreams: List<PipedStream>? = null,
    val audioStreams: List<PipedStream>? = null,
    val livestream: Boolean? = null,
    val subtitle: List<PipedSubtitle>? = null
)

data class PipedStream(
    val url: String? = null,
    val quality: String? = null,
    val mimeType: String? = null,
    val codec: String? = null,
    val bitrate: Long? = null,
    val initStart: Long? = null,
    val initEnd: Long? = null,
    val indexStart: Long? = null,
    val indexEnd: Long? = null,
    val width: Int? = null,
    val height: Int? = null,
    val fps: Int? = null
)

data class PipedSubtitle(
    val url: String? = null,
    val mimeType: String? = null,
    val name: String? = null,
    val code: String? = null,
    val autoGenerated: Boolean? = null
)

data class PipedSearchResponse(
    val items: List<PipedSearchItem>? = null,
    val nextpage: String? = null,
    val suggestion: String? = null,
    val corrected: Boolean? = null
)

data class PipedSearchItem(
    val url: String? = null,
    val title: String? = null,
    val thumbnail: String? = null,
    val uploaderName: String? = null,
    val uploaderUrl: String? = null,
    val uploaderAvatar: String? = null,
    val views: Long? = null,
    val duration: Long? = null,
    val uploadedDate: String? = null,
    val uploaded: Long? = null,
    val type: String? = null
)

data class PipedTrendingResponse(
    val items: List<PipedTrendingItem>? = null,
    val nextpage: String? = null
)

data class PipedTrendingItem(
    val url: String? = null,
    val title: String? = null,
    val thumbnail: String? = null,
    val uploaderName: String? = null,
    val uploaderUrl: String? = null,
    val uploaderAvatar: String? = null,
    val views: Long? = null,
    val duration: Long? = null,
    val uploaded: Long? = null,
    val uploadedDate: String? = null
)

data class PipedChannelResponse(
    val name: String? = null,
    val avatarUrl: String? = null,
    val bannerUrl: String? = null,
    val description: String? = null,
    val subscriberCount: Long? = null,
    val relatedStreams: List<PipedSearchItem>? = null,
    val nextpage: String? = null
)

data class PipedPlaylistResponse(
    val name: String? = null,
    val thumbnailUrl: String? = null,
    val uploaderName: String? = null,
    val uploaderUrl: String? = null,
    val uploaderAvatar: String? = null,
    val relatedStreams: List<PipedSearchItem>? = null,
    val nextpage: String? = null
)

interface PipedApiService {

    @GET("trending")
    suspend fun getTrending(
        @Query("region") region: String = "US"
    ): PipedTrendingResponse

    @GET("search")
    suspend fun search(
        @Query("q") query: String,
        @Query("filter") filter: String = "all"
    ): PipedSearchResponse

    @GET("search")
    suspend fun searchNextPage(
        @Query("q") query: String,
        @Query("nextpage") nextPage: String
    ): PipedSearchResponse

    @GET("streams/{id}")
    suspend fun getVideoStreams(
        @Path("id") videoId: String
    ): PipedVideoResponse

    @GET("channels/{id}")
    suspend fun getChannel(
        @Path("id") channelId: String
    ): PipedChannelResponse

    @GET("playlists/{id}")
    suspend fun getPlaylist(
        @Path("id") playlistId: String
    ): PipedPlaylistResponse

    @GET("trending")
    suspend fun getTrendingNextPage(
        @Query("nextpage") nextPage: String
    ): PipedTrendingResponse

    @GET("channels/{id}")
    suspend fun getChannelNextPage(
        @Path("id") channelId: String,
        @Query("nextpage") nextPage: String
    ): PipedChannelResponse

    @GET("playlists/{id}")
    suspend fun getPlaylistNextPage(
        @Path("id") playlistId: String,
        @Query("nextpage") nextPage: String
    ): PipedPlaylistResponse

    @GET("suggestions")
    suspend fun getSuggestions(
        @Query("query") query: String
    ): List<String>
}
