package com.freedomplay.app.data.api.piped

import com.google.gson.annotations.SerializedName
import retrofit2.http.GET
import retrofit2.http.Path
import retrofit2.http.Query

data class PipedVideoResponse(
    @SerializedName("title") val title: String? = null,
    @SerializedName("uploader") val uploader: String? = null,
    @SerializedName("uploaderUrl") val uploaderUrl: String? = null,
    @SerializedName("thumbnailUrl") val thumbnailUrl: String? = null,
    @SerializedName("duration") val duration: Long? = null,
    @SerializedName("views") val views: Long? = null,
    @SerializedName("uploaded") val uploaded: Long? = null,
    @SerializedName("uploadDate") val uploadDate: String? = null,
    @SerializedName("description") val description: String? = null,
    @SerializedName("videoStreams") val videoStreams: List<PipedStream>? = null,
    @SerializedName("audioStreams") val audioStreams: List<PipedStream>? = null,
    @SerializedName("livestream") val livestream: Boolean? = null,
    @SerializedName("subtitles") val subtitle: List<PipedSubtitle>? = null
)

data class PipedStream(
    @SerializedName("url") val url: String? = null,
    @SerializedName("quality") val quality: String? = null,
    @SerializedName("mimeType") val mimeType: String? = null,
    @SerializedName("codec") val codec: String? = null,
    @SerializedName("bitrate") val bitrate: Long? = null,
    @SerializedName("initStart") val initStart: Long? = null,
    @SerializedName("initEnd") val initEnd: Long? = null,
    @SerializedName("indexStart") val indexStart: Long? = null,
    @SerializedName("indexEnd") val indexEnd: Long? = null,
    @SerializedName("width") val width: Int? = null,
    @SerializedName("height") val height: Int? = null,
    @SerializedName("fps") val fps: Int? = null
)

data class PipedSubtitle(
    @SerializedName("url") val url: String? = null,
    @SerializedName("mimeType") val mimeType: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("code") val code: String? = null,
    @SerializedName("autoGenerated") val autoGenerated: Boolean? = null
)

data class PipedSearchResponse(
    @SerializedName("items") val items: List<PipedSearchItem>? = null,
    @SerializedName("nextpage") val nextpage: String? = null,
    @SerializedName("suggestion") val suggestion: String? = null,
    @SerializedName("corrected") val corrected: Boolean? = null
)

data class PipedSearchItem(
    @SerializedName("url") val url: String? = null,
    @SerializedName("title") val title: String? = null,
    @SerializedName("thumbnail") val thumbnail: String? = null,
    @SerializedName("uploaderName") val uploaderName: String? = null,
    @SerializedName("uploaderUrl") val uploaderUrl: String? = null,
    @SerializedName("uploaderAvatar") val uploaderAvatar: String? = null,
    @SerializedName("views") val views: Long? = null,
    @SerializedName("duration") val duration: Long? = null,
    @SerializedName("uploadedDate") val uploadedDate: String? = null,
    @SerializedName("uploaded") val uploaded: Long? = null,
    @SerializedName("type") val type: String? = null
)

data class PipedTrendingResponse(
    @SerializedName("items") val items: List<PipedTrendingItem>? = null,
    @SerializedName("nextpage") val nextpage: String? = null
)

data class PipedTrendingItem(
    @SerializedName("url") val url: String? = null,
    @SerializedName("title") val title: String? = null,
    @SerializedName("thumbnail") val thumbnail: String? = null,
    @SerializedName("uploaderName") val uploaderName: String? = null,
    @SerializedName("uploaderUrl") val uploaderUrl: String? = null,
    @SerializedName("uploaderAvatar") val uploaderAvatar: String? = null,
    @SerializedName("views") val views: Long? = null,
    @SerializedName("duration") val duration: Long? = null,
    @SerializedName("uploaded") val uploaded: Long? = null,
    @SerializedName("uploadedDate") val uploadedDate: String? = null
)

data class PipedChannelResponse(
    @SerializedName("name") val name: String? = null,
    @SerializedName("avatarUrl") val avatarUrl: String? = null,
    @SerializedName("bannerUrl") val bannerUrl: String? = null,
    @SerializedName("description") val description: String? = null,
    @SerializedName("subscriberCount") val subscriberCount: Long? = null,
    @SerializedName("relatedStreams") val relatedStreams: List<PipedSearchItem>? = null,
    @SerializedName("nextpage") val nextpage: String? = null
)

data class PipedPlaylistResponse(
    @SerializedName("name") val name: String? = null,
    @SerializedName("thumbnailUrl") val thumbnailUrl: String? = null,
    @SerializedName("uploaderName") val uploaderName: String? = null,
    @SerializedName("uploaderUrl") val uploaderUrl: String? = null,
    @SerializedName("uploaderAvatar") val uploaderAvatar: String? = null,
    @SerializedName("relatedStreams") val relatedStreams: List<PipedSearchItem>? = null,
    @SerializedName("nextpage") val nextpage: String? = null
)

interface PipedApiService {

    @GET("trending")
    suspend fun getTrending(
        @Query("region") region: String = "US"
    ): List<PipedTrendingItem>

    @GET("search")
    suspend fun search(
        @Query("q") query: String,
        @Query("filter") filter: String = "all"
    ): PipedSearchResponse

    @GET("search")
    suspend fun searchNextPage(
        @Query("q") query: String,
        @Query("nextpage") nextPage: String
    ): PipedSearchResponse

    @GET("streams/{id}")
    suspend fun getVideoStreams(
        @Path("id") videoId: String
    ): PipedVideoResponse

    @GET("channels/{id}")
    suspend fun getChannel(
        @Path("id") channelId: String
    ): PipedChannelResponse

    @GET("playlists/{id}")
    suspend fun getPlaylist(
        @Path("id") playlistId: String
    ): PipedPlaylistResponse

    @GET("trending")
    suspend fun getTrendingNextPage(
        @Query("nextpage") nextPage: String
    ): PipedTrendingResponse

    @GET("channels/{id}")
    suspend fun getChannelNextPage(
        @Path("id") channelId: String,
        @Query("nextpage") nextPage: String
    ): PipedChannelResponse

    @GET("playlists/{id}")
    suspend fun getPlaylistNextPage(
        @Path("id") playlistId: String,
        @Query("nextpage") nextPage: String
    ): PipedPlaylistResponse

    @GET("suggestions")
    suspend fun getSuggestions(
        @Query("query") query: String
    ): List<String>
}
