package com.streamvault.player.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Check
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class CaptionTrack(
    val id: String,
    val language: String,
    val label: String,
    val isAutoGenerated: Boolean = false,
    val isSelected: Boolean = false
)

@Composable
fun CaptionSelectorSheet(
    visible: Boolean,
    captions: List<CaptionTrack>,
    selectedCaption: CaptionTrack?,
    onCaptionSelected: (CaptionTrack?) -> Unit,
    onDismiss: () -> Unit
) {
    BottomSheetContainer(
        visible = visible,
        title = "Captions",
        onDismiss = onDismiss
    ) {
        LazyColumn(
            modifier = Modifier
                .fillMaxWidth()
                .padding(bottom = 32.dp)
        ) {
            item {
                CaptionItem(
                    label = "Off",
                    isSelected = selectedCaption == null,
                    onClick = { onCaptionSelected(null) }
                )
            }
            if (captions.isNotEmpty()) {
                item {
                    HorizontalDivider(color = Color.White.copy(alpha = 0.1f), modifier = Modifier.padding(vertical = 4.dp))
                }
                captions.forEach { track ->
                    item {
                        CaptionItem(
                            label = track.language + if (track.isAutoGenerated) " (Auto-generated)" else "",
                            isSelected = selectedCaption?.id == track.id,
                            onClick = { onCaptionSelected(track) }
                        )
                    }
                }
            }
        }
    }
}

@Composable
private fun CaptionItem(
    label: String,
    isSelected: Boolean,
    onClick: () -> Unit
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick)
            .padding(horizontal = 20.dp, vertical = 14.dp)
    ) {
        Text(
            text = label,
            color = if (isSelected) Color(0xFFE11D48) else Color.White,
            fontSize = 14.sp,
            fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal,
            modifier = Modifier.weight(1f)
        )
        if (isSelected) {
            Icon(
                imageVector = Icons.Default.Check,
                contentDescription = "Selected",
                tint = Color(0xFFE11D48)
            )
        }
    }
}
