package com.freedomplay.app.data.repository

import com.freedomplay.app.data.api.piped.PipedApiService
import com.freedomplay.app.data.api.piped.PipedSearchItem
import com.freedomplay.app.data.api.piped.PipedSearchResponse
import com.freedomplay.app.data.api.piped.PipedStream
import com.freedomplay.app.data.api.piped.PipedSubtitle
import com.freedomplay.app.data.api.piped.PipedTrendingItem
import com.freedomplay.app.data.api.piped.PipedTrendingResponse
import com.freedomplay.app.data.api.piped.PipedVideoResponse
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever

class StreamRepositoryTest {

    private lateinit var pipedApi: PipedApiService
    private lateinit var repository: StreamRepository

    @Before
    fun setup() {
        pipedApi = mock()
        repository = StreamRepository(pipedApi)
    }

    // --- getTrending ---

    @Test
    fun `getTrending returns mapped items`() = runTest {
        val trendingResponse = PipedTrendingResponse(
            items = listOf(
                PipedTrendingItem(
                    url = "/watch?v=abc12345678",
                    title = "Trending Video",
                    thumbnail = "https://img.youtube.com/vi/abc12345678/mqdefault.jpg",
                    uploaderName = "Creator",
                    views = 50000L,
                    duration = 300L
                )
            )
        )
        whenever(pipedApi.getTrending()).thenReturn(trendingResponse)

        val result = repository.getTrending()

        assertTrue(result.isSuccess)
        val items = result.getOrNull()!!
        assertEquals(1, items.size)
        assertEquals("Trending Video", items[0].title)
        assertEquals("abc12345678", items[0].videoId)
        assertEquals(50000L, items[0].views)
    }

    @Test
    fun `getTrending returns empty list when no items`() = runTest {
        whenever(pipedApi.getTrending()).thenReturn(PipedTrendingResponse(items = null))

        val result = repository.getTrending()

        assertTrue(result.isSuccess)
        assertEquals(0, result.getOrNull()?.size)
    }

    @Test
    fun `getTrending returns failure on API error`() = runTest {
        whenever(pipedApi.getTrending()).thenThrow(RuntimeException("Network error"))

        val result = repository.getTrending()

        assertTrue(result.isFailure)
    }

    // --- search ---

    @Test
    fun `search returns mapped items`() = runTest {
        val searchResponse = PipedSearchResponse(
            items = listOf(
                PipedSearchItem(
                    url = "/watch?v=xyz12345678",
                    title = "Search Result",
                    thumbnail = "https://img.youtube.com/vi/xyz12345678/mqdefault.jpg",
                    uploaderName = "Channel",
                    views = 1000L,
                    duration = 120L
                )
            )
        )
        whenever(pipedApi.search("test query")).thenReturn(searchResponse)

        val result = repository.search("test query")

        assertTrue(result.isSuccess)
        val items = result.getOrNull()!!
        assertEquals(1, items.size)
        assertEquals("Search Result", items[0].title)
        assertEquals("xyz12345678", items[0].videoId)
    }

    @Test
    fun `search returns empty when no results`() = runTest {
        whenever(pipedApi.search("empty")).thenReturn(PipedSearchResponse(items = null))

        val result = repository.search("empty")

        assertTrue(result.isSuccess)
        assertEquals(0, result.getOrNull()?.size)
    }

    // --- getStreams ---

    @Test
    fun `getStreams returns mapped stream`() = runTest {
        val videoResponse = PipedVideoResponse(
            title = "Test Video",
            uploader = "Test Channel",
            duration = 600L,
            views = 10000L,
            videoStreams = listOf(
                PipedStream(url = "https://example.com/v", quality = "720p", mimeType = "video/mp4", width = 1280, height = 720)
            ),
            audioStreams = listOf(
                PipedStream(url = "https://example.com/a", quality = "128kbps", mimeType = "audio/mp4", bitrate = 128000L)
            ),
            subtitle = listOf(
                PipedSubtitle(url = "https://example.com/sub", mimeType = "text/vtt", name = "English", code = "en", autoGenerated = true)
            )
        )
        whenever(pipedApi.getVideoStreams("abc12345678")).thenReturn(videoResponse)

        val result = repository.getStreams("abc12345678")

        assertTrue(result.isSuccess)
        val stream = result.getOrNull()!!
        assertEquals("Test Video", stream.title)
        assertEquals("Test Channel", stream.uploader)
        assertEquals(600L, stream.duration)
        assertEquals(10000L, stream.views)
        assertEquals(1, stream.videoStreams.size)
        assertEquals("720p", stream.videoStreams[0].quality)
        assertEquals(1, stream.audioStreams.size)
        assertEquals(1, stream.subtitles.size)
        assertEquals("en", stream.subtitles[0].code)
    }

    @Test
    fun `getStreams handles empty streams`() = runTest {
        val videoResponse = PipedVideoResponse(
            title = "Empty",
            videoStreams = null,
            audioStreams = null,
            subtitle = null
        )
        whenever(pipedApi.getVideoStreams("empty123456")).thenReturn(videoResponse)

        val result = repository.getStreams("empty123456")

        assertTrue(result.isSuccess)
        val stream = result.getOrNull()!!
        assertEquals(0, stream.videoStreams.size)
        assertEquals(0, stream.audioStreams.size)
        assertEquals(0, stream.subtitles.size)
    }

    @Test
    fun `getStreams returns failure on API error`() = runTest {
        whenever(pipedApi.getVideoStreams("fail1234567")).thenThrow(RuntimeException("404"))

        val result = repository.getStreams("fail1234567")

        assertTrue(result.isFailure)
    }

    // --- getSuggestions ---

    @Test
    fun `getSuggestions returns list`() = runTest {
        whenever(pipedApi.getSuggestions("test")).thenReturn(listOf("test query 1", "test query 2"))

        val result = repository.getSuggestions("test")

        assertTrue(result.isSuccess)
        assertEquals(2, result.getOrNull()?.size)
    }

    @Test
    fun `getSuggestions returns empty list`() = runTest {
        whenever(pipedApi.getSuggestions("xyz")).thenReturn(emptyList())

        val result = repository.getSuggestions("xyz")

        assertTrue(result.isSuccess)
        assertEquals(0, result.getOrNull()?.size)
    }
}
